version: '3.9'

services:

  nginx:
    container_name: ui_nginx
    restart: always
    build:
      context: .
      dockerfile: nginx/Dockerfile
    environment:
      BACKEND_API: api:4000
      NGINX_PORT: 80
      NGINX_HTTPS_PORT: 443
      FORCE_HTTPS: 'false'
      REACT_APP_SENTRY_API: https://5bb4e6d8480b4bda905a5715821206bb@o1177838.ingest.sentry.io/6288957
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    networks:
      - mynet

  api:
    container_name: api_express
    build:
      context: ./api
      dockerfile: prod.Dockerfile
    depends_on:
      - mongodb
    ports:
      - 4000
    restart: always
    environment:
      NODE_ENV: production
      SECRET: e42d8dd28adf34fc489044d5aa21e5166f22a6ef
      MONGODB_URI: mongodb://mongodb:27017/
      MONGODB_DB_MAIN: portfolio_db
      SENTRY_API: https://dd48265c46c54f5db36bc7c645936650@o1177838.ingest.sentry.io/6288993
      PORT: 4000
    networks:
      - mynet

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
        MONGO_INITDB_DATABASE: portfolio_db
    ports:
      - 27017
    volumes:
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mynet


networks:
  mynet:
