---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - mongo-pv.yaml
  - ingress.yaml
  - mongo-pvc.yaml

images:
  - name: front-nginx
    newName: lucferbux/nginx:VERSION-1509e71-SNAPSHOT
  - name: api-express
    newName: lucferbux/api:VERSION-1509e71-SNAPSHOT

namespace: portfolio-app-local
